// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifvuxqfzatedotkesmmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmdnV4cWZ6YXRlZG90a2VzbW15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyNzMxMzMsImV4cCI6MjA1MTg0OTEzM30.gQ4vbpHrX-3ppqlRcijnc-MPMh3A27ozfTTrpEp9pi8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);